### ISSUE TITLE
Where are buttons?

### ISSUE THREAD

**Issue by lujo777** [timoniq/vkbottle#13]
- Who we are?
- We're coders! 
- What we'd like to see in this lib?
- BUTTONS!!!!!

Please add button support!

**Comment by timoniq** [comment]
I have just lost all my examples of buttons usage, but now I'm ready to invent readme's secton
Now you can use keyboard generator like this:
`[[row], [{'text': 'Your Button'}, {'text': 'Your Red Button', 'color': 'negative'}]]`
I am working on fixes now

**Comment by timoniq** [comment]
Now, done
