### ISSUE TITLE
Use asynchronous framework in README

### ISSUE THREAD

**Issue by prostomarkeloff** [timoniq/vkbottle#5]
Use asynchronous framework in README; Delete `bot.process` method; Use `bot.emulate` in callback-api section.

**Comment by timoniq** [comment]
Ok, i am going to fix readme section today. Check syntax amendments in VK topic for now

**Comment by prostomarkeloff** [comment]
> Ok, i am going to fix readme section today. Check syntax amendments in VK topic for now

i was banned
