### ISSUE TITLE
Don't use `asyncio.ensure_future'.

### ISSUE THREAD

**Issue by prostomarkeloff** [timoniq/vkbottle#7]
It's really bad way, in most parts of code it's unnecessary. I will create PR for fix that.

**Comment by timoniq** [comment]
It is not an option. It is just a view about how users can promise their events for VKBottle main emulator. I understand all disadvantages of this way and suggest lots of replacements.
PR are welcome! Good luck

**Comment by prostomarkeloff** [comment]
Okay. Basically, `ensure_future` method uses for `stopping` coroutines, as generators. It's stop task (nearby first `await` construction) and return `Future` object which you may await.
